### ISSUE TITLE
demo in custom data

### ISSUE THREAD

**Issue by athrunsunny** [nianticlabs/scoring-without-correspondences#4]
Do I need to regenerate the fundamentals.npy file when using this model in custom scenes?

**Comment by axelBarroso** [comment]
Hello, 

Thank you for your interest in our work! 

Yes, the fundamentals.npy file is specific to your custom image pair. It contains the candidate fundamental matrices, eg, proposed by a RANSAC loop. We give more details on the paper about how we generate our fundamental matrices candidates in Section 4.6.

Hope this helps!
